parse_config:
  zmk_additional_includes:
    - "modules/zmk/helpers/include"
  zmk_preamble: |
    #include <zmk-helpers/key-labels/42.h>
    #define CONFIG_WIRELESS
layout: {qmk_keyboard: sofle/rev2}
